# Generated by Django 3.2.9 on 2021-11-10 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='ustoz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.ustoz'),
            preserve_default=False,
        ),
    ]
