# Generated by Django 3.2.9 on 2021-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_fan_ustoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('sahifa', models.SmallIntegerField()),
                ('tur', models.CharField(choices=[('badiy', 'badiy'), ('ilmiy', 'ilmiy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.SmallIntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=5)),
            ],
        ),
    ]
