# Generated by Django 3.2.9 on 2021-11-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_kitob_muallif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateField()),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kitob')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.muallif')),
            ],
        ),
    ]
